FROM nvcr.io/nvidia/pytorch:24.08-py3

WORKDIR /workspace/KNK-VF
COPY pyproject.toml README.md ./
COPY knk ./knk
RUN python -m pip install --upgrade pip && python -m pip install -e ".[train]"

ENV NVIDIA_VISIBLE_DEVICES=all
ENV TORCH_NCCL_ASYNC_ERROR_HANDLING=1
